name: Pre release

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - README.md

env:
  CARGO_TERM_COLOR: always

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create ZipFile Name
        id: zipName
        run: echo "::set-output name=filename::'gnome-x11-gesture-daemon.$(date --iso-8601).$(git rev-parse --short HEAD).zip'"
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libinput-dev
      - name: Build
        run: cargo build --release

      - name: Create Zip
        run: |
          zip "${{ steps.zipName.outputs.filename }}" \
          target/release/gesture_improvements_gesture_daemon \
          install.sh \
          uninstall.sh \
          gesture_improvements_gesture_daemon.service

      - name: Upload archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.zipName.outputs.filename }}"
          path: ${{ steps.zipName.outputs.filename }}"
